import tkinter as tk
window = tk.Tk()
window.title("i don't know")
window.geometry('400x400')
menubar = tk.Menu(window)
fileMenu = tk.Menu(menubar, tearoff = False)
fileMenu.add_command(label = 'new game')
fileMenu.add_command(label = 'cheat command')
fileMenu.add_separator()
fileMenu.add_command(label = 'exit')
menubar.add_cascade(label = '檔案', menu = fileMenu)
 
fileMenu2 = tk.Menu(menubar, tearoff = False)
fileMenu2.add_command(label = 'game setting')
fileMenu2.add_command(label = '畫面 setting')

subMenu = tk.Menu(menubar, tearoff = False)
subMenu.add_command(label = '遊戲優化max')
subMenu.add_command(label = 'attack all ememy')
fileMenu2.add_cascade(label = '進階setting', menu = subMenu)
menubar.add_cascade(label = '選項', menu = fileMenu2)
string = tk.StringVar()
string.set('minecraft python')
gender = tk.StringVar()
gender.set('boy')
def selection():
    label.config(text = 'i like ' + string.get() + ", i'm a " + gender.get())
    
label = tk.Label(window, bg = '#f00', text = '尚未選擇')
label.pack()
radio1 = tk.Radiobutton(window, text = 'minecraft python', variable = string, value = 'minecraft python', command = selection)
radio1.pack()
radio2 = tk.Radiobutton(window, text = 'tkinter', variable = string, value = 'tkinter', command = selection)
radio2.pack()
radio3 = tk.Radiobutton(window, text = 'pygame', variable = string, value = 'pygame', command = selection)
radio3.pack()
radio4 = tk.Radiobutton(window, text = 'boy', variable = gender, value = 'boy', command = selection)
radio4.pack()
radio5 = tk.Radiobutton(window, text = 'girl', variable = gender, value = 'girl', command = selection)
radio5.pack()
window.config(menu = menubar)
window.mainloop()